[package]
name = "tmou-mapa-backend"
version = "0.1.0"
authors = ["Mila Votradovec <me@milavotradovec.cz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
