openapi: 3.0.0
info:
  title: Domaci hra
  version: '1.0'
  description: TMOU domaci hra
  contact:
    name: Petr Valasek
    url: tmou.cz
    email: petr.valasek@volny.cz
servers:
  - url: 'http://localhost:3000'
paths:
  '/game/{teamSecretPhrase}/info':
    parameters:
      - schema:
          type: string
        name: teamSecretPhrase
        in: path
        required: true
        description: ''
    get:
      summary: Your GET endpoint
      tags:
        - teams
        - tmou
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamState'
        '404':
          description: Not Found
      operationId: get-teams-teamSecretPhrase
      description: get list of points of interests
      requestBody: {}
  '/game/{teamSecretPhrase}/pois':
    parameters:
      - schema:
          type: string
        name: teamSecretPhrase
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodes'
        '404':
          description: Not Found
      operationId: get-game-teamSecretPhrase-nodes
      description: get points of interests as nodes and ways
  '/game/{teamSecretPhrase}/grid':
    parameters:
      - schema:
          type: string
        name: teamSecretPhrase
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grid'
        '404':
          description: Not Found
      operationId: get-game-teamSecretPhrase-tiles
      description: get addresses of map tiles for background rendering
  '/game/{teamSecretPhrase}/action':
    parameters:
      - schema:
          type: string
        name: teamSecretPhrase
        in: path
        required: true
    post:
      summary: ''
      operationId: post-game-teamSecretPhrase-operation
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
        '404':
          description: Not Found
      description: perform an action upon node
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeAction'
components:
  schemas:
    Node:
      title: Node
      type: object
      description: Single node
      x-tags:
        - node
        - teams
      properties:
        id:
          type: string
        x:
          type: number
          format: float
          example: 0.58
          minimum: 0
          maximum: 1
          exclusiveMinimum: false
          exclusiveMaximum: false
          description: x pos relative to displayed map
        'y':
          type: number
          format: float
          example: 0
          minimum: 0
          maximum: 1
          exclusiveMaximum: false
          description: y pos relative to displayed map
        type:
          type: string
          enum:
            - way
            - junction
            - org
            - team
            - puzzle
          example: way
        data:
          type: string
          description: 'additional node type-specific data, e. g. url for puzzle'
          example: Mastene Redkvicky
      required:
        - id
        - x
        - 'y'
        - type
    Nodes:
      title: Nodes
      description: List of nodes
      x-tags:
        - teams
      type: array
      items:
        $ref: '#/components/schemas/Node'
      x-examples:
        example-1: {}
    TeamState:
      title: Info
      type: object
      description: ''
      properties:
        ranking:
          type: integer
          description: current ranking in the game
        leader:
          type: string
          description: first on this puzzle
        timeBehind:
          type: string
          format: time
          example: '00:22:00'
          description: time behind first on this puzzle
        position:
          type: string
          description: Node ID
      required:
        - position
    Tile:
      title: Tile
      type: object
      description: 'map tile with relative coordinates (0..# of cols, 0..# of rows)'
      properties:
        url:
          type: string
          example: /images/1770/8955.png
        x:
          type: integer
          example: 2
          minimum: 0
        'y':
          type: integer
          example: 2
          minimum: 0
        zoom:
          type: integer
          minimum: 1
          maximum: 19
      required:
        - url
        - x
        - 'y'
    Grid:
      title: Grid
      type: object
      properties:
        columns:
          type: integer
          minimum: 1
        rows:
          type: integer
          minimum: 1
        columnWidth:
          type: integer
          minimum: 1
        rowHeight:
          type: integer
          minimum: 1
        tiles:
          type: array
          items:
            $ref: ''
    Way:
      title: Waz
      type: object
      description: ordered collection of node IDs connected into a shape. Can be closed.
      properties:
        nodes:
          type: array
          description: node IDs
          items:
            type: string
        '':
          type: string
        closed:
          type: boolean
          default: 'false'
      required:
        - nodes
    Ways:
      title: Ways
      type: array
      description: node id
      items:
        $ref: '#/components/schemas/Way'
    Pois:
      title: Pois
      type: object
      properties:
        nodes:
          $ref: '#/components/schemas/Nodes'
        ways:
          $ref: '#/components/schemas/Ways'
    NodeAction:
      title: NodeAction
      type: object
      properties:
        nodeId:
          type: string
        action:
          type: string
          enum:
            - go
            - discover
            - requestChat
            - requestVideo
          example: go
      required:
        - nodeId
        - action
      x-examples: {}
