name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


defaults:
  run:
    working-directory: ./tmou-mapa-backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Set ENV vars
      run: |
        echo "TMOU_GAME_START=2020-11-06T20:00:00+01:00"  >> $GITHUB_ENV
        echo "TMOU_GAME_EXECUTION_MODE=On" >> $GITHUB_ENV
        echo "TMOU_GAME_END=2020-11-07T12:00:00+01:00" >> $GITHUB_ENV
    - name: Run tests
      env:
        ROCKET_DATABASES: '{postgres={url="${{ secrets.DB_URL }}",pool_size=1}}'
      run: cargo test --verbose
